import type { Metadata } from "next";
import { DM_Sans, Ms_Madi, Noto_Serif_Display } from "next/font/google";
import localFont from "next/font/local";
import Link from "next/link";
import Image from "next/image";
import Loader from "@/components/Loader";
import SideNav from "@/components/SideNav";
import TransitionProvider from "@/components/TransitionProvider";
import "./globals.css";

const akros = localFont({
  src: "../public/font/Akros-Regular.otf",
  variable: "--font-akros",
});

const msMadi = Ms_Madi({
  variable: "--font-script",
  subsets: ["latin"],
  weight: "400",
});

const notoSerifDisplay = Noto_Serif_Display({
  variable: "--font-serif",
  subsets: ["latin"],
  weight: ['400', '700']
});

const dmSans = DM_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ['400', '500', '700']
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${notoSerifDisplay.variable} ${dmSans.variable} ${akros.variable} ${msMadi.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col overflow-x-hidden">
        <Loader />
        <Link href="/" className="fixed top-6 left-6 md:left-16 z-50 hover:opacity-70 transition-opacity">
          <Image
            src="/images/logo/logo.png"
            alt="Rumami logo"
            width={80}
            height={80}
            priority
          />
        </Link>
        <TransitionProvider>
          {children}
        </TransitionProvider>
        <SideNav />
      </body>
    </html>
  );
}
